#!/bin/bash

###################################################################################
### This script will use JAMF. The admin user will need to have a secureToken. ####
### The Jamf helper tool would be easier to use, but I wanted to make this more ###
### accessible to other MDM solutions. So I will use Finder. ######################
###################################################################################

##########################################################################################################
### Create an Encrypted String ###########################################################################
### this will be needed to pass credentials securely https://github.com/brysontyrrell/EncryptedStrings ###
### The Copyright below is to stay in terms of fair use ##################################################
##########################################################################################################

###################################################################################
### JSS Paramaters ################################################################
### $4 = Username Encrypted String ################################################
### $5 = Password Encrypted String ################################################
### $6 = macOS Version | Example: Monterey ########################################
### $7 = Install macOS path | Example: Install\ macOS\ Monterey.app ###############
###################################################################################

#################################
### String Encrypted Username ###
#################################
SALTUN=""
KUN=""
UN=$(echo "$4" | /usr/bin/openssl enc -aes256 -md md5 -d -a -A -S "$SALTUN" -k "$KUN")

#################################
### String Encrypted Password ###
#################################
SALTPW=""
KPW=""
PW=$(echo "$5" | /usr/bin/openssl enc -aes256 -md md5 -d -a -A -S "$SALTPW" -k "$KPW")

###################################################################
### This will store the logged in user's C badge to a variable. ###
###################################################################
userName=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

###################################
### Activate the Finder window. ###
###################################
osascript -e 'tell application "Finder"
	if not running then
    		run
    		delay 0.25
	end if
	activate
end tell'

################################################################################
### This will prompt the user for their password and store it in a variable. ###
################################################################################
userPassword=$(osascript -e '
tell application "Finder"
   display dialog "Please enter your Computer password." with hidden answer default answer ""
   set userPassword to the (text returned of the result)
end tell')

#######################################################################################################
### Store the output of the sysadminctl command into a variable to use it for error handling later. ###
#######################################################################################################
output=$(sudo sysadminctl -adminUser "$adminUser" -adminPassword "$adminPassword" -secureTokenOn $userName -password $userPassword 2>&1)

########################################################################################################
### Error handling to see if the password entered is the same password used to log into the machine. ###
########################################################################################################

################################################################################################
### Searches for the output "Done". If this exist then the sysadminctl command will execute. ###
################################################################################################
if [[ $output == *"Done"* ]]; then
    ##############################################################################################################################
    ### Command used to provide the user a secureToken. The admin user must have a secure token or this command will not work. ###
    ### You can always check the JAMF policy logs to see if the user is experiencing an issue. ###################################
    ##############################################################################################################################
    sudo sysadminctl -adminUser "$adminUser" -adminPassword "$adminPassword" -secureTokenOn $userName -password $userPassword
    
    ################################
    ### GUI dialog for the user. ###
    ################################
    title='MacOS FileVault Encryption'
	osascript -e "display dialog \"Your password has been successfully synced with FileVault!\" buttons {\"OK\"} default button \"OK\" with title \"$title\""
else
    ################################
    ### GUI dialog for the user. ###
    ################################
    title='MacOS FileVault Encryption'
	osascript -e "display dialog \"The password entered did not match your password on this computer! Please quit and re-run the Self-Service policy to try again.\" buttons {\"Quit (Your password was not synced!)\"} default button \"Quit (Your password was not synced!)\" with title \"$title\""
fi
